### ISSUE TITLE
just a reminder for you tht7....

### ISSUE THREAD

**Issue by zxzzz8** [zxzzz8/PersonalHub#1]
![6067331](https://user-images.githubusercontent.com/20977838/53774734-588da480-3ef8-11e9-8ca5-6fbebf36fe89.png)

@tht7 ....

how long are you gonna keep this icon ^ ?
XD

its not even your favorite color blue, rather, orange is the exact opposite of it X3

**Comment by zxzzz8** [comment]
hmmm, i wonder if this link will last after you update your icon....
https://avatars1.githubusercontent.com/u/6067331?s=400&v=4
it is a github icon so mby it will stay the same? 
or will it update to your new icon? or will be removed as your new icon will have a new link? 
lol

-

oh and btw, despite not being a collaborator in this repository, 
did you get a notification for this? sense i @tht7 pinged you....

wait did you get 2 notifications coz i pinged you in the comment here as well? XD

**Comment by tht7** [comment]
😰😅 Notification was received indeed!
And I didn't bother with the icon
and about the link I have a feeling it will just update to the new icon

**Comment by tht7** [comment]
AND YES I GOT 2 NOTIFICATIONS😣

**Comment by zxzzz8** [comment]
so.... you actually ok w this icon? 0_0
plz don't be ok w it, its also a bit confusing w all the similar github users that left it that way as well X=

**Comment by tht7** [comment]
eeee there updated

**Comment by zxzzz8** [comment]
thank you ^^
